update cicd

diff --git a/.github/workflows/inspect.yml b/.github/workflows/inspect.yml
--- a/.github/workflows/inspect.yml
+++ b/.github/workflows/inspect.yml
@@ -4,30 +4,41 @@ on: [pull_request]
 
 jobs:
   inspect:
-    runs-on: self-hosted
+    runs-on: ubuntu-latest      
+
     steps:
-      - uses: actions/checkout@v3
-      - name: Restore Packages
-        run: dotnet restore
-      - name: build solution before analysis
-        run: dotnet build -c Debug -warnaserror
+    - name: Git checkout
+      uses: actions/checkout@v3
+    
+    - name: Start MongoDB
+      uses: supercharge/mongodb-github-action@1.8.0
+      with:
+        mongodb-version: '5.0'
+        mongodb-replica-set: rs0
         
-      - name: determine changed files
-        uses: lots0logs/gh-action-get-changed-files@2.1.4
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-      - name: run resharper
-        run: |
-          changed_files=$(jq --raw-output 'join(";")' "${HOME}/files.json")
-          echo "Changed files: $changed_files"
-          jb inspectcode --severity=WARNING --format=Json --output=_rs_inspections --include="$changed_files" HVZ.sln || echo "ReSharper failed, likely because the filter resulted in no files being analyzed"
-      - name: process resharper inspections
-        run: |
-          if [ -d "./_rs_inspections" ]; then
-            for filename in ./_rs_inspections/*.json; do
-              jq --raw-output '.problems[] | "::\(.problem_class.severity) file=\(.file | gsub("\\\\";"/") | sub("\\$PROJECT_DIR\\$/";"")),line=\(.line),col=\(.offset)::\(.description)"' "$filename"
-            done
-          fi
-      - name: check code formatting
-        run: |
-          dotnet format --verify-no-changes --report=_format_report.json || python .github/workflows/process_format_report.py
+    - name: Install .NET 7.0.x
+      uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: "7.0.x"
+
+    - name: Restore Packages
+      run: dotnet restore
+
+    - name: build solution before analysis
+      run: dotnet build -c Debug -warnaserror
+
+    - name: run resharper
+      run: |
+        changed_files=$(jq --raw-output 'join(";")' "${HOME}/files.json")
+        echo "Changed files: $changed_files"
+        jb inspectcode --severity=WARNING --format=Json --output=_rs_inspections --include="$changed_files" HVZ.sln || echo "ReSharper failed, likely because the filter resulted in no files being analyzed"
+    - name: process resharper inspections
+      run: |
+        if [ -d "./_rs_inspections" ]; then
+          for filename in ./_rs_inspections/*.json; do
+            jq --raw-output '.problems[] | "::\(.problem_class.severity) file=\(.file | gsub("\\\\";"/") | sub("\\$PROJECT_DIR\\$/";"")),line=\(.line),col=\(.offset)::\(.description)"' "$filename"
+          done
+        fi
+    - name: check code formatting
+      run: |
+        dotnet format --verify-no-changes --report=_format_report.json || python .github/workflows/process_format_report.py
